version: '3'
services:
  db:
    image: postgres:11.6
  web:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
      DOCKER: "true"
